
package com.vp.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.webservice.vp.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @param state
     * @return
     *     returns com.vp.webservice.service.ArrayOfXsdAnyType
     */
    @WebMethod
    @WebResult(name = "getProductsReturn", targetNamespace = "http://service.webservice.vp.com", partName = "getProductsReturn")
    public ArrayOfXsdAnyType getProducts(
        @WebParam(name = "state", targetNamespace = "http://service.webservice.vp.com", partName = "state")
        String state);

    /**
     * 
     * @param productName
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "addProductReturn", targetNamespace = "http://service.webservice.vp.com", partName = "addProductReturn")
    public boolean addProduct(
        @WebParam(name = "productName", targetNamespace = "http://service.webservice.vp.com", partName = "productName")
        String productName);

}
